language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  - emacs --version
  - cask exec ert-runner
