language: emacs-lisp
sudo: required
arch:
  repos:
  packages:
    - python
    - emacs
    - cask
  script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
    - cask exec ert-runner

